### ISSUE TITLE
Calling location.reload() opens in embedded window

### ISSUE THREAD

**Issue by tlhunter** [pwa-builder/pwabuilder-ios#38]
When calling `location.reload()`, the application window remains in the same state, but the page is then opened in a new embedded view. Closing that view returns to the existing application window.

Interestingly, calling something like `location.href = '/';` doesn't result in this behavior.

I'm curious; is the code that PWABuilder generates able to hook into these operations? Or is it sort of at the mercy of the embedded web view that Apple provides?

**Comment by JudahGabriel** [comment]
Thanks for reporting this. It might be related to your query string. Investigating.

**Comment by JudahGabriel** [comment]
Yep, the issue was indeed your query string and path. 

To fix this, go into Settings.swift and set allowedOrigin to be your host, e.g. "foo.com" - no HTTPS, no path, no query string. Then location.reload will work.

I've applied this patch to PWABuilder, so if you regenerate your package with PWABuilder, it'll include the fix.
